### ISSUE TITLE
Ground up instructions for Visual Studio newbie

### ISSUE THREAD

**Issue by coderextreme** [awonnink/vSlam#1]
Can you create some ground up instructions for a Visual Studio newbie?  Thanks!

**Comment by awonnink** [comment]
Hi John,

I am happy to help you.
Can you be more specific in what is troubling you? Are you trying to setup the browser, the server or both?
The readme on the v-Slam browser project instructs what is necessary to run the browser project in Unity. It's starts by using 'our' server, but this can be changed in Assets/Scripts/Slam/Constants.cs (BaseHomeUrl)

Regards,

Albert Jan


________________________________
Van: John Carlson <notifications@github.com>
Verzonden: donderdag 21 maart 2019 10:54
Aan: awonnink/vSlam
CC: Subscribed
Onderwerp: [awonnink/vSlam] Ground up instructions for Visual Studio newbie (#1)


Can you create some ground up instructions for a Visual Studio newbie? Thanks!

**Comment by awonnink** [comment]
I think I can build, but I haven’t been able to debug.   I was able to set project type (Release/Debug) and the architecture.

Sent from Mail for Windows 10
